
PLAYERS_COUNT = 1

USE_MOUSE = False
USE_WEBCAM = False

DEBUG = True
DEBUG_WEBCAM = False
DEUBG_WEBCAM_WITH_WINDOW = False
DEBUG_TRAIL = False
DEBUG_BONUSES = False
FULLSCREEN = False
DEBUG_ROBOT = True

DEBUG_WITHOUT_ROBOT = DEBUG and not DEBUG_ROBOT
DEBUG_SINGLE_PLAYER = DEBUG and PLAYERS_COUNT == 1

